# -*- coding: utf-8 -*-
"""Credit-Scoring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzuoezjNMjZ5tIooyhnVkAm2f21H7cMn
"""

from google.colab import drive
drive.mount('/content/drive/')

"""Google drive **mounted**

"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier



# Load the train data
train_data = pd.read_csv('/content/drive/MyDrive/Credit_Score_ds/data_train.csv')

train_data

"""Imported data (train_data) from drive. **Here the label 0 represents people who are unable to pay their credits whereas label = 1 represents people who pay their credits**.  """

drop_columns  = ['Score_level', 'Score_class', 'Score_point', 'Changed_phone_number', 'INPS_mln_sum', 'label' ]
features = train_data.drop(drop_columns, axis=1)
features.head()

"""drop_columns variable contains irregular columns (not required) and the `label column which is fitted into the target variable below `"""

target = train_data['label']
target.head()

"""**Preprocessing of the data**"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

"""We have used MinMaxScaler() to scale the features in a dataset to a common range (0-1).
Benifits:


1.   Data is interpretable
2.   Data is formed into compatible format



"""

features = scaler.fit_transform(features)

features

"""Above is the data after preprocessing."""

target

knn = KNeighborsClassifier(n_neighbors= 5)

"""setting the number of neighbors for KNN classification  """

from sklearn.model_selection import train_test_split

"""importing sklearn.model_selection to split the data into **`80/20`** (train/test) ratio"""

xtrain, xtest, ytrain, ytest = train_test_split(features, target, test_size = 0.2, random_state = 1)

"""**`------------------First(KNN)--------------------------------`**"""

knn.fit(xtrain, ytrain)

"""Training of the model"""

ypred = knn.predict(xtest)

"""Predictions are stored in `ypred` and the array is displayed below\."""

ypred

ytest

"""**Below is the accuracy of the model.**  """

accuracy = np.mean(ypred == ytest)

accuracy

"""**Conclusion:**


1.   KNN classification accuracy is `96.6%`
2.   Accuracy > 90% = model can be used in production


"""

score  = knn.score(xtest, ytest)

score

"""score = `96.6%`

**`------------------Second--------------------------------`**

Now lets focus on second algo = Decision Tree
"""

#predict using Decision Tree
from sklearn.tree import DecisionTreeClassifier

"""importing decision tree

"""

model = DecisionTreeClassifier()
model.fit(xtrain, ytrain)

"""Training the model"""

answer = model.predict(xtest)
answer

"""Predicted the `label` for testing data"""

accuracy_DT = np.mean(answer == ytest)
accuracy_DT

model.score(xtest, ytest)

"""Score accuracy  = `99.2%`

**`------------------Third--------------------------------`**
"""

#imported LR (logistic regression)
from sklearn.linear_model import LogisticRegression

"""model imported"""

lr_model = LogisticRegression()
lr_model.fit(xtrain, ytrain)

lr_pred = lr_model.predict(xtest)

"""predictions made for the model"""

lr_model.score(xtest, ytest)

"""Model accuracy = 98.5 %
