# -*- coding: utf-8 -*-
"""Credit-Scoring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzuoezjNMjZ5tIooyhnVkAm2f21H7cMn
"""

from google.colab import drive
drive.mount('/content/drive/')

"""Google drive **mounted**

"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
